"""CaseMaster + Inv_OccuranceTime: the statistical backbone.

Sampling weights (crime-type mix, hour-of-day, day-of-week) are UNIFORM
placeholders, not NCRB-derived, per explicit user decision
(placeholder-until-populated — see ncrb_reference.py TODO). Swap the
`random.choice(...)` calls below for `random.choices(..., weights=...)`
against ncrb_reference constants once that file is populated; the sampling
call sites are marked PLACEHOLDER-WEIGHT so they're easy to find.

CrimeRegisteredDate spans 2023-07-01 -> today so both IPC (pre-2024-07-01)
and BNS (post) sections have rows to attach to downstream.

BriefFacts is synthetic narrative text (never real FIR language, per
CLAUDE.md) generated by narratives.py. A NETWORK_RATE slice of
gang-shaped offences (Murder/Dacoity/Robbery/NDPS/Kidnapping/Arms Act) get
richer multi-accused narratives instead of the flat one-liner, because this
is the content the chatbot and the graph module actually reason over — a
dataset that's all one-off strangers gives Phase 9's graph layer nothing to
show. generate_case_master returns (rows, case_plans): case_plans is a
CaseMasterID-keyed dict of {is_network, accused_count, gang_name, ...} —
NOT written to the CaseMaster CSV (would be undeclared-column schema
drift) — passed straight to case_children.generate_accused() so the
Accused/gang rows it creates agree with what BriefFacts describes.
"""

from __future__ import annotations

import datetime
import random
from typing import Any

from data_generation.generators import narratives
from data_generation.utils import id_sequence, write_csv

random.seed(43)

NETWORK_RATE = 0.30  # of NETWORK_ELIGIBLE_SUBHEADS cases only, see narratives.py.
# Higher than real-world organized-crime prevalence — deliberately, so the
# persona pool actually recurs often enough for the graph module to show
# a visible network at demo scale instead of one being lost in the noise
# floor of coincidental one-off name collisions. Tune down once dataset
# scale is >=10k cases and/or the graph demo has enough signal already.

REGISTERED_START = datetime.date(2023, 7, 1)
REGISTERED_END = datetime.date.today()

# CaseCategory LookupValue -> single digit for CrimeNo, order matches
# lookups.CASE_CATEGORIES ["FIR", "UDR", "PAR", "NCR", "MVC"].
CATEGORY_DIGIT = {"FIR": 1, "UDR": 2, "PAR": 3, "NCR": 4, "MVC": 5}

PLACE_TYPES = ["Residence", "Public Road", "Commercial Establishment",
               "Open Field", "ATM/Bank", "Educational Institution",
               "Public Transport", "Other"]

# Karnataka bounding box, coarse — not per-district precision.
LAT_RANGE = (11.5, 18.5)
LON_RANGE = (74.0, 78.5)

_serial_counters: dict[tuple[int, int], int] = {}


def _next_serial(district_id: int, year: int) -> int:
    key = (district_id, year)
    _serial_counters[key] = _serial_counters.get(key, 0) + 1
    return _serial_counters[key]


def _build_crime_no(category_digit: int, district_id: int, unit_id: int, year: int) -> str:
    serial = _next_serial(district_id, year)
    return (
        f"{category_digit:01d}{district_id:04d}{unit_id:04d}{year:04d}{serial:05d}"
    )


def _random_registered_date() -> datetime.date:
    span_days = (REGISTERED_END - REGISTERED_START).days
    return REGISTERED_START + datetime.timedelta(days=random.randint(0, span_days))


def _random_datetime_on(day: datetime.date) -> datetime.datetime:
    return datetime.datetime(day.year, day.month, day.day,
                              random.randint(0, 23), random.randint(0, 59))


def generate_case_master(
    district_rows: list[dict[str, Any]],
    district_rowid_map: dict[int, int],
    unit_rows: list[dict[str, Any]],
    unit_rowid_map: dict[int, int],
    employee_rows: list[dict[str, Any]],
    employee_rowid_map: dict[int, int],
    case_category_rows: list[dict[str, Any]],
    case_category_rowid_map: dict[int, int],
    gravity_rows: list[dict[str, Any]],
    gravity_rowid_map: dict[int, int],
    crimehead_rows: list[dict[str, Any]],
    crimehead_rowid_map: dict[int, int],
    crimesubhead_rows: list[dict[str, Any]],
    crimesubhead_rowid_map: dict[int, int],
    case_status_rows: list[dict[str, Any]],
    case_status_rowid_map: dict[int, int],
    court_rows: list[dict[str, Any]],
    court_rowid_map: dict[int, int],
    count: int = 10_000,
) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]]]:
    ids = id_sequence(1)
    rows = []
    case_plans: dict[int, dict[str, Any]] = {}

    # Units grouped by district so PoliceStationID_FK stays geographically
    # consistent with DistrictID_FK on the same case.
    units_by_district: dict[int, list[dict[str, Any]]] = {}
    for u in unit_rows:
        units_by_district.setdefault(u["DistrictID_FK"], []).append(u)

    for _ in range(count):
        district = random.choice(district_rows)  # PLACEHOLDER-WEIGHT (uniform, not NCRB volume ratio)
        district_rowid = district_rowid_map[district["DistrictID"]]
        candidate_units = units_by_district.get(district_rowid, unit_rows)
        unit = random.choice(candidate_units)

        category = random.choice(case_category_rows)  # PLACEHOLDER-WEIGHT
        gravity = random.choice(gravity_rows)  # PLACEHOLDER-WEIGHT
        crimehead = random.choice(crimehead_rows)  # PLACEHOLDER-WEIGHT
        subheads_for_head = [
            s for s in crimesubhead_rows
            if s["CrimeHeadID_FK"] == crimehead_rowid_map[crimehead["CrimeHeadID"]]
        ]
        subhead = random.choice(subheads_for_head)
        status = random.choice(case_status_rows)  # PLACEHOLDER-WEIGHT
        employee = random.choice(employee_rows)
        court = random.choice(court_rows)

        registered_date = _random_registered_date()  # PLACEHOLDER-WEIGHT (uniform across span)
        info_received = _random_datetime_on(registered_date) - datetime.timedelta(
            hours=random.randint(0, 48))
        incident_to = info_received - datetime.timedelta(hours=random.randint(0, 72))
        incident_from = incident_to - datetime.timedelta(hours=random.randint(0, 24))

        place_type = random.choice(PLACE_TYPES)  # PLACEHOLDER-WEIGHT

        plan = narratives.plan_case_narrative(subhead["CrimeHeadName"], NETWORK_RATE, random)
        brief_facts = narratives.build_brief_facts(
            subhead["CrimeHeadName"], place_type, district["DistrictName"],
            category["LookupValue"], plan, random,
        )

        case_master_id = next(ids)
        case_plans[case_master_id] = plan
        rows.append({
            "CaseMasterID": case_master_id,
            "CrimeNo": _build_crime_no(
                CATEGORY_DIGIT[category["LookupValue"]],
                district["DistrictID"], unit["UnitID"], registered_date.year,
            ),
            "CaseNo": f"CASE-{case_master_id:07d}",
            "CrimeRegisteredDate": registered_date.isoformat(),
            "PolicePersonID_FK": employee_rowid_map[employee["EmployeeID"]],
            "PoliceStationID_FK": unit_rowid_map[unit["UnitID"]],
            "CaseCategoryID_FK": case_category_rowid_map[category["CaseCategoryID"]],
            "GravityOffenceID_FK": gravity_rowid_map[gravity["GravityOffenceID"]],
            "CrimeMajorHeadID_FK": crimehead_rowid_map[crimehead["CrimeHeadID"]],
            "CrimeMinorHeadID_FK": crimesubhead_rowid_map[subhead["CrimeSubHeadID"]],
            "CaseStatusID_FK": case_status_rowid_map[status["CaseStatusID"]],
            "CourtID_FK": court_rowid_map[court["CourtID"]],
            "IncidentFromDate": incident_from.isoformat(sep=" "),
            "IncidentToDate": incident_to.isoformat(sep=" "),
            "InfoReceivedPSDate": info_received.isoformat(sep=" "),
            "latitude": round(random.uniform(*LAT_RANGE), 6),
            "longitude": round(random.uniform(*LON_RANGE), 6),
            "BriefFacts": brief_facts,
        })

    # schema.md naming drift: CaseMasterID->CseMasterID, InfoReceivedPSDate->
    # InfoRecievedPSDate, latitude->Latitude, longitude->Longitude,
    # GravityOffenceID_FK built without the _FK suffix.
    write_csv(rows, "CaseMaster", column_rename={
        "CaseMasterID": "CseMasterID",
        "InfoReceivedPSDate": "InfoRecievedPSDate",
        "latitude": "Latitude",
        "longitude": "Longitude",
        "GravityOffenceID_FK": "GravityOffenceID",
    })
    return rows, case_plans


def generate_occurance_time(
    case_master_rows: list[dict[str, Any]],
    case_master_rowid_map: dict[int, int],
) -> list[dict[str, Any]]:
    ids = id_sequence(1)
    rows = []
    for case in case_master_rows:
        incident_from = datetime.datetime.fromisoformat(case["IncidentFromDate"])
        hour = incident_from.hour
        if 5 <= hour < 12:
            bucket = "Morning"
        elif 12 <= hour < 17:
            bucket = "Afternoon"
        elif 17 <= hour < 21:
            bucket = "Evening"
        else:
            bucket = "Night"

        rows.append({
            "OccuranceTimeID": next(ids),
            "CaseMasterID_FK": case_master_rowid_map[case["CaseMasterID"]],
            "DayOfWeek": incident_from.strftime("%A"),
            "TimeOfDayBucket": bucket,
            "PlaceOfOccurrenceType": random.choice(PLACE_TYPES),  # PLACEHOLDER-WEIGHT
            "PlaceOfOccurrenceDescription": "",
            "IsOutdoor": random.random() < 0.4,  # PLACEHOLDER-WEIGHT
        })

    # schema.md naming drift: both PlaceOfOccurrence* columns built as
    # PlaceOfOccurance* (missing the 'e').
    write_csv(rows, "Inv_OccuranceTime", column_rename={
        "PlaceOfOccurrenceType": "PlaceOfOccuranceType",
        "PlaceOfOccurrenceDescription": "PlaceOfOccuranceDescription",
    })
    return rows
